import type { Metadata } from "next";
import { Geist, Geist_Mono, Mali, Prompt, Comic_Relief } from "next/font/google";
import "./globals.css";

const maliFont = Mali({
	weight: ["200", "300", "400", "500", "600", "700"],
	variable: "--font-mali",
	subsets: ["latin", "thai"],
});

const promptFont = Prompt({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-prompt",
	subsets: ["latin", "thai"],
});

const comicReliefFont = Comic_Relief({
	weight: ["400", "700"],
	variable: "--font-comic-relief",
	subsets: ["latin"],
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "???",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="th" className={`${geistSans.variable} ${geistMono.variable} ${maliFont.variable} ${promptFont.variable} ${comicReliefFont.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
